### ISSUE TITLE
Will be updated to new version?

### ISSUE THREAD

**Issue by Pesegato** [ontherunvaro/DraconiusGO-Assets#1]
And/or how to extract the assets?

**Comment by ontherunvaro** [comment]
Sorry, I didn't even realize there was any interest in this repo. I extract the assets using [this tool](https://github.com/Perfare/UnityStudio).

I don't currently have the time to update them (nor do I play the game anymore since they nerfed the fun out of it) but feel free to extract and submit a pull request if you want.
